### ISSUE TITLE
Enable source mapping of less file

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt-less#13]
This is really useful for debugging as you can look at specific CSS files vs. one giant file.

`sourceMap: { sourceMapFileInline: true }`

Edit: That doesn't seem to fully work. Might need to combine it with other options

http://lesscss.org/usage/#programmatic-usage

**Comment by alallier** [comment]
Note: It doesn't seem like the options object is exposed for the compiler

**Comment by alallier** [comment]
This could probably be closed? As source mapping is working and exposed now. The only reason you would possibly want to keep it open is if you want to discuss making it an on by default choice

**Comment by kethinov** [comment]
reopen if you think it should be on by default

**Comment by alallier** [comment]
Personally I think it should be an on by default. Especially for people who might not realize they are missing it. Open to counter arguments.
